name: Install Package

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  # TODO: refactor build when https://github.community/t5/GitHub-Actions/reusing-sharing-inheriting-steps-between-jobs-declarations/td-p/37849
  import-models:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ 3.6, 3.7 ]

    steps:
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install keras-fsl as dependency
        run: |
          python -m pip install --upgrade pip
          python -m pip install git+https://github.com/few-shot-learning/Keras-FewShotLearning.git@${{ github.ref }}
      - name: Import keras_fsl.models
        run: |
          python -c "from keras_fsl import models"
